---
- name: Backup NXOS switches config
  hosts: nxos_hosts

  tasks:
    - name: Backup NXOS config
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}"
          dir_path: /home/ansible/ansible_nxos_ios_vlans/backup


- name: Backup IOS switches config
  hosts: ios_hosts

  tasks:
    - name: Backup IOS config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}"
          dir_path: /home/ansible/ansible_nxos_ios_vlans/backup
...
