---
ansible_host: 172.16.100.4

l2_interfaces:
  - name: port-channel1
    trunk:
      native_vlan: 1
      allowed_vlans: 201, 202, 203, 204, 205
  - name: port-channel101
    trunk:
      native_vlan: 1
      allowed_vlans: 201, 202, 203, 204, 205

l3_interfaces:
  - name: Vlan201
    ipv4:
      - address: 10.1.1.4/24
  - name: Vlan202
    ipv4:
      - address: 10.1.2.4/24
  - name: Vlan203
    ipv4:
      - address: 10.1.3.4/24
  - name: Vlan204
    ipv4:
      - address: 10.1.4.4/24
  - name: Vlan205
    ipv4:
      - address: 10.1.5.4/24
...
